from sqlmodel import Session, select, delete
from models import Company, DailyPrice
from typing import List
from datetime import date


def create_company(db: Session, company: Company) -> Company:
    """
    Creates a new company in the database.
    """
    db.add(company)
    db.commit()
    db.refresh(company)  # get the autogenerated id
    return company


def save_daily_prices(db: Session, prices: List[DailyPrice]):
    """
    Saves a list of new daily prices to the database.
    """
    for price in prices:
        db.add(price)
    db.commit()


def get_all_companies(db: Session) -> List[Company]:
    """
    Fetches all companies from the database.
    """
    return db.exec(select(Company)).all()


def get_company_by_ticker(db: Session, ticker: str) -> Company | None:
    """
    Fetches a company by its ticker.
    """
    statement = select(Company).where(Company.ticker == ticker.upper())
    return db.exec(statement).first()


def get_latest_date_for_company(db: Session, company_id: int) -> date | None:
    """
    Returns the most recent date of the data stored for
    the specified company.
    """
    statement = (
        select(DailyPrice.date)
        .where(DailyPrice.company_id == company_id)
        .order_by(DailyPrice.date.desc())
    )

    result = db.exec(statement).first()
    return result


def get_earliest_date_for_company(db: Session, company_id: int) -> date | None:
    """
    Returns the earliest date of the data stored for the specified company.
    """
    statement = (
        select(DailyPrice.date)
        .where(DailyPrice.company_id == company_id)
        .order_by(DailyPrice.date.asc())
    )

    result = db.exec(statement).first()
    return result


def get_prices_for_company(
    db: Session,
    company_id: int,
    start_date: date | None = None,
    end_date: date | None = None,
) -> List[DailyPrice]:
    """
    Fetches all daily prices for a given company,
    optionally filtered by date.
    """
    statement = select(DailyPrice).where(DailyPrice.company_id == company_id)
    if start_date:
        statement = statement.where(DailyPrice.date >= start_date)
    if end_date:
        statement = statement.where(DailyPrice.date <= end_date)

    statement = statement.order_by(DailyPrice.date)
    return db.exec(statement).all()


def delete_prices_for_company(db: Session, company_id: int) -> int:
    """
    Deletes all daily prices for a given company.
    Returns number of rows deleted (caller commits).
    """
    statement = delete(DailyPrice).where(DailyPrice.company_id == company_id)
    result = db.exec(statement)
    return result.rowcount or 0


def delete_company(db: Session, company_id: int) -> int:
    """
    Deletes a company by id. Returns number of rows deleted (caller commits).
    """
    statement = delete(Company).where(Company.id == company_id)
    result = db.exec(statement)
    return result.rowcount or 0


def delete_company_and_prices(db: Session, company_id: int) -> tuple[int, int]:
    """
    Deletes prices first (to satisfy FK constraints), then the company.
    Commits once. Returns (prices_deleted, companies_deleted).
    """
    prices_deleted = delete_prices_for_company(db, company_id)
    companies_deleted = delete_company(db, company_id)
    db.commit()
    return prices_deleted, companies_deleted
